write_mode = "Overwrite"

max_width = 120
ideal_width = 120
fn_call_width = 100

fn_args_density = "Compressed"

enum_trailing_comma = true
match_block_trailing_comma = true
struct_trailing_comma = "Always"
wrap_comments = true

report_todo = "Always"
report_fixme = "Always"
