title = "mdBook Documentation"
description = "Create book from markdown files. Like Gitbook but implemented in Rust"
author = "Mathieu David"

[output.html]
additional-css = ["my_custom.css"]
mathjax-support = true
